### ISSUE TITLE
Incorrect "not found" diagnostic

### ISSUE THREAD

**Issue by Rolv-Apneseth** [zk-org/zk-nvim#161]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

In a note, I have a code extract from a `Cargo.toml`, which is giving a diagnostic message: `not found`. This is because it uses the same syntax as linking to a note I guess, but I would prefer if anything within a code block would be ignored by `zk-nvim`

### How to reproduce?

Use code block, diagnostic is on the line with `[[bench]]`:

    ```toml
    [dev-dependencies]
    criterion = { version = "0.5.1", features = ["html_reports"] }

    [[bench]]
    name = "main"
    path = "benches/bench.rs"
    harness = false
    ```

### zk configuration

```toml
[lsp.diagnostics]
wiki-title = "hint"
dead-link = "error"
```

### Neovim configuration

```viml
zk-nvim opts:


{
        picker = "telescope",
        lsp = {
            config = {
                cmd = { "zk", "lsp" },
                name = "zk",
            },
            auto_attach = {
                enabled = true,
                filetypes = { "markdown" },
            },
        },
    }
```
```


### Environment

```bash
zk 0.14.0
system: Linux 6.7.5-arch1-1 x86_64 GNU/Linux
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
