### ISSUE TITLE
Duplicate entries in :ZkBacklinks

### ISSUE THREAD

**Issue by WhyNotHugo** [zk-org/zk-nvim#189]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [X] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Entries for :ZkBacklinks are all duplicate. If I call `require("fzf-lua").lsp_references()`, all entries shown are also duplicated.

If I remove `require("zk").setup({})` from the config, the picker for `require("fzf-lua").lsp_references()` no longer duplicates entries.

### How to reproduce?

0. Ensure that the configuration file includes `require("zk").setup({})`.
1. `:ZkBacklinks`

### zk configuration

```toml
[notebook]
dir = "~/zk"

[note]
filename = "{{id}}"

[format.markdown]
hashtags = true
link-format = "[{{title}}]({{rel-path}})"

[lsp.diagnostics]
dead-link = "error"

[alias]
n = "zk new"
e = "zk edit --interactive"
journal = "zk new --no-input ~/zk/journal/"

[group.journal]
paths = ["journal"]

[group.journal.note]
filename = "{{format-date now}}"
```

### Neovim configuration

I don't have a minimal template yet, full config is:

https://git.sr.ht/~whynothugo/dotfiles/tree/f34b44434fa8a103e764584ea618dbdef301a438/item/home/.config/nvim/init.lua

### Environment

```bash
zk 
system: Linux 6.10.10-0-edge x86_64 Linux
NVIM v0.10.0
Build type: MinSizeRel
LuaJIT 2.1.1710398010
Run "nvim -V1 -v" for more info
```
