### ISSUE TITLE
Completions Not Working

### ISSUE THREAD

**Issue by dandeandean** [zk-org/zk-nvim#233]
### Check if applicable

- [x] I have searched the existing issues (**required**)
- [x] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

Seems like the completions are not triggering when using the `[[`.
We can see from the image that the lsp is attached & giving me that error.
This may be related to #228, because I am gettting that error as well.
[[<img width="358" alt="Image" src="https://github.com/user-attachments/assets/5cfe256f-0d98-4f48-90cb-74f212637c72" />

### How to reproduce?

1. Open a note in with nvim
2. Enter `[[`

### zk configuration

```toml
I haven't changed the default lsp config, but here's the rest 

[note]
language = "en"
template = "default.md"
[extra]
[group.journal]
paths = ["daily"]

[group.journal.note]
filename = "{{format-date now}}"
template = "daily.md"

# MARKDOWN SETTINGS
[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "nvim"
[lsp]

[lsp.diagnostics]
dead-link = "error"
[lsp.completion]
[filter]
[alias]
e = "nvim -c \":ZkNotes\""
```

### Neovim configuration

```viml
return {
	"zk-org/zk-nvim",
	config = function()
		require("zk").setup({
			picker = "telescope",
			lsp = {
				config = {
					cmd = { "zk", "lsp" },
					name = "zk",
				},
				auto_attach = {
					enabled = true,
					filetypes = { "markdown" },
				},
				-- Make sure to set $ZK_NOTEBOOK_DIR
				vim.keymap.set("n", "<leader>zk", "<CMD>ZkNotes<CR>", { desc = "Zk" }),
				vim.keymap.set("n", "<leader>zt", "<CMD>ZkTags<CR>", { desc = "Zk Tags" }),
				vim.keymap.set("n", "<leader>zb", "<CMD>ZkBacklinks<CR>", { desc = "Zk Backlinks" }),
				vim.keymap.set("n", "<leader>znn", "<CMD>ZkNew<CR>", { desc = "Zk New New" }),
			},
		})
	end,
}

Also using "echasnovski/mini.completion" for the completions.
```

### Environment

```bash
zk 0.15.1
system: Darwin 23.6.0 arm64
NVIM v0.12.0-dev-192+g65170e8dad
Build type: Release
LuaJIT 2.1.1744317938
Run "nvim -V1 -v" for more info
---
I'm getting the same behavior on nvim 11.1
NVIM v0.11.1
Build type: Release
LuaJIT 2.1.1744318430
Run "nvim -V1 -v" for more info
```
